name: simple-chat

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  cache:
    image: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    image: staleread/chat-api:2.0.0
    environment:
      PORT: 8000
      SERVER_URL: ${SERVER_URL}
      RATE_LIMIT: ${RATE_LIMIT}
      RATE_LIMIT_TIME_WINDOW: ${RATE_LIMIT_TIME_WINDOW}
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      REDIS_URL: ${REDIS_URL}
      PASSWORD_SALT: ${PASSWORD_SALT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
